[build-system]
requires = [
    "colorama",
    "defusedxml",
    "macholib",
    "msgpack>=1.0.0",
    "pefile",
    "pycryptodomex",
    "pyelftools",
    "setuptools",
    "toml",
    "wheel",
]
build-backend = "setuptools.build_meta"